import { Channel } from "mygo-runtime";
import { Devices, Download, Environment, Flash, Massflash, Provision, Recovery, events, type Config, type Device, type Options, type Progress, type ProvisionOptions, type Status } from "./mygo";
const $ = <T extends HTMLElement>(selector: string) => document.querySelector<T>(selector)!;
const pages = ["Environment", "Devices", "Flash", "Massflash", "Provision", "Recovery", "Download", "Settings"] as const;
type Page = typeof pages[number];
let page: Page = "Environment";
let config: Config = { l4t: "", workspace: "", downloadDir: "", logLimit: 5000, proxy: { enabled: false, url: "", rememberCredentials: false } };
let host: Status = { host: false, root: false, checks: [] };
let devices: Device[] = [];
let flashOptions: Options = { board: "jetson-orin-nano-devkit-super", device: "nvme0n1p1", nvme: "tools/kernel_flash/flash_l4t_t234_nvme.xml", qspi: "bootloader/generic/cfg/flash_t234_qspi.xml", erase: false, showLogs: true };
let provisionOptions: ProvisionOptions = { username: "dev", password: "", hostname: "jetson", publicKey: "", overlay: "", autologin: false, packages: "", script: "", clearKeys: true, clearMachineId: true, firstBoot: true };
let running = false;
const lines: string[] = [];
function log(message: string) { lines.push(message); if (lines.length > (config.logLimit || 5000)) lines.shift(); const el = $("#log"); el.textContent = lines.join("\n"); if ($<HTMLInputElement>("#autoscroll").checked) el.scrollTop = el.scrollHeight; }
function fail(error: unknown) { const message = error instanceof Error ? error.message : String(error); $("#status").textContent = "Failed"; log("ERROR: " + message); }
function val(id: string) { return $<HTMLInputElement>("#" + id).value.trim(); }
function check(id: string) { return $<HTMLInputElement>("#" + id).checked; }
function safe(value: string) { return value.replace(/[&<>"']/g, ch => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[ch]!); }
function confirmDanger(message: string) { return window.confirm(`${message}\n\nThis operation may change or erase device data. Continue?`); }
async function stream<T = Progress>(task: (channel: Channel<T>) => Promise<void>, output: (item: T) => void) { if (running) return; running = true; $("#status").textContent = "Running"; try { await task(new Channel<T>(output)); $("#status").textContent = "Completed"; log("Operation completed"); } catch (error) { fail(error); } finally { running = false; render(); } }
function path(id: string, title: string, current: string, directory = true) { return `<label>${title}<span class="row"><input id="${id}" value="${safe(current)}"/><button type="button" data-path="${id}" data-dir="${directory}">Browse</button></span></label>`; }
function shell(title: string, description: string, body: string) { $("#panel").innerHTML = `<h1>${title}</h1><p class="lead">${description}</p>${body}`; document.querySelectorAll<HTMLButtonElement>("[data-path]").forEach(button => button.onclick = () => void Environment.browse(button.dataset.dir === "true").then(result => { if (result) $<HTMLInputElement>("#" + button.dataset.path).value = result; }).catch(fail)); }
function gate() { return !host.host ? `<div class="warning">Flashing requires a Linux x86_64 host (Linux_for_Tegra, USB, root). Not supported on this platform.</div>` : !host.root ? `<div class="warning">Root required: restart with pkexec or sudo to enable flashing.</div>` : ""; }
function flashForm() { return `<div class="card"><h3>Target configuration</h3><div class="grid"><label>Board preset<select id="preset"><option value="">Custom</option></select></label><label>Board<input id="board" value="${safe(flashOptions.board)}" list="boards"/><datalist id="boards"></datalist></label><label>External device<input id="device" value="${safe(flashOptions.device)}"/></label><label>NVMe layout XML<input id="nvme" value="${safe(flashOptions.nvme)}"/></label><label>QSPI layout XML<input id="qspi" value="${safe(flashOptions.qspi)}"/></label><label class="check"><input id="erase" type="checkbox" ${flashOptions.erase ? "checked" : ""}/> Erase all storage</label><label class="check"><input id="showLogs" type="checkbox" ${flashOptions.showLogs ? "checked" : ""}/> Detailed logs</label></div><p class="hint">rootdev: internal · network: usb0 · Erase all destroys target data.</p></div>`; }
function readFlash() { flashOptions = { board: val("board"), device: val("device"), nvme: val("nvme"), qspi: val("qspi"), erase: check("erase"), showLogs: check("showLogs") }; }
async function fillPresets() { const select = $<HTMLSelectElement>("#preset"); const presets = await Environment.presets(); for (const preset of presets) select.add(new Option(preset.name, preset.name)); select.onchange = () => { const chosen = presets.find(preset => preset.name === select.value); if (chosen) { flashOptions = chosen.options; for (const key of ["board", "device", "nvme", "qspi"] as const) $<HTMLInputElement>("#" + key).value = chosen.options[key]; $<HTMLInputElement>("#erase").checked = chosen.options.erase; $<HTMLInputElement>("#showLogs").checked = chosen.options.showLogs; } }; const report = await Environment.detect(config.l4t); for (const board of report.boards) $("#boards").append(new Option(board)); }
function render() { const nav = $("#nav"); nav.replaceChildren(); for (const item of pages) { const button = document.createElement("button"); button.textContent = item; button.className = page === item ? "active" : ""; button.onclick = () => { page = item; render(); }; nav.append(button); } $("#host").textContent = host.host ? `LINUX x86_64 · ${host.root ? "ROOT READY" : "ROOT REQUIRED"}` : "NON-LINUX FLASHING DISABLED"; $("#device-count").textContent = `${devices.filter(device => device.mode === "recovery").length} recovery devices`;
  if (page === "Environment") { shell("Environment", "Inspect your Linux for Tegra BSP and host dependencies.", `${gate()}<div class="card">${path("l4t", "Linux_for_Tegra directory", config.l4t)}<div class="actions"><button class="primary" id="detect">Run diagnostics</button><button id="root" ${!host.host || host.root ? "disabled" : ""}>Restart as root</button></div></div><div class="card" id="report">Run diagnostics to inspect BSP.</div>`); $("#detect").onclick = () => void (async () => { try { config.l4t = val("l4t"); await Environment.saveConfig(config); const report = await Environment.detect(config.l4t); const output = $("#report"); output.replaceChildren(); const heading = document.createElement("h3"); heading.textContent = `${report.version || "Unknown version"} · ${report.boards.length} boards`; output.append(heading); for (const item of [...report.checks, ...host.checks]) { const row = document.createElement("div"); row.className = "report"; const name = document.createElement("span"); name.textContent = item.name; const hint = document.createElement("span"); hint.className = item.status; hint.textContent = `${item.status}: ${item.hint}`; row.append(name, hint); output.append(row); } } catch (error) { fail(error); } })(); $("#root").onclick = () => void Environment.restartAsRoot().catch(fail); }
  if (page === "Devices") { shell("Devices", "Recovery USB devices refresh every two seconds on Linux.", `${gate()}<div class="card" id="device-list"></div>`); const output = $("#device-list"); output.textContent = devices.length ? "" : "No Recovery or initrd devices found."; for (const device of devices) { const row = document.createElement("div"); row.className = "report"; row.textContent = `${device.path} · 0955:${device.product} · ${device.mode}`; output.append(row); } }
  if (page === "Flash" || page === "Massflash") { const mass = page === "Massflash"; shell(mass ? "Massflash" : "Flash device", mass ? "Generate MFI offline or flash matching Recovery devices in parallel." : "Run NVIDIA's official initrd flashing tool for one Recovery device.", `${gate()}${flashForm()}${mass ? `<div class="card grid"><label>Concurrency limit<input id="count" type="number" value="5" min="1" max="64"/></label>${path("mfi", "Extracted MFI directory", config.workspace)}<p class="hint wide">Offline generation may require BOARDID. Output: mfi_&lt;board&gt;.tar.gz. All devices must be identical hardware.</p></div>` : ""}<div class="actions"><button class="primary" id="start" ${!host.host || !host.root || (!mass && !devices.some(device => device.mode === "recovery")) ? "disabled" : ""}>${mass ? "Generate MFI" : "Start flash"}</button>${mass ? `<button id="bulk" ${!host.host || !host.root || !devices.some(device => device.mode === "recovery") ? "disabled" : ""}>Flash MFI devices</button>` : ""}<button id="cancel">Cancel</button></div>`); void fillPresets().catch(fail); $("#start").onclick = () => { readFlash(); if (!confirmDanger(flashOptions.erase ? "ERASE ALL enabled. Wipe the connected Jetson?" : "Start flashing the connected Jetson?")) return; if (mass) void stream(channel => Massflash.generate(config.l4t, flashOptions, Number(val("count")), channel), log); else void stream(channel => Flash.start(config.l4t, flashOptions, channel), log); }; if (mass) $("#bulk").onclick = () => { if (!confirmDanger("Flash all connected matching devices?")) return; void stream(channel => Massflash.flash(val("mfi"), Number(val("count")), check("showLogs"), channel), log); }; $("#cancel").onclick = () => void (mass ? Massflash.cancel() : Flash.cancel()).catch(fail); }
  if (page === "Provision") { shell("Provision rootfs", "Create a user, install packages and customize rootfs using a non-interactive chroot.", `${gate()}<div class="warning">Scripts run as root with no TTY. Review the entire script before running it.</div><div class="card grid"><label>Username<input id="username" value="${safe(provisionOptions.username)}"/></label><label>Hostname prefix<input id="hostname" value="${safe(provisionOptions.hostname)}"/></label><label>Password<span class="row"><input id="password" type="password" value="${safe(provisionOptions.password)}"/><button id="show-password">Show</button><button id="random">Generate</button></span></label>${path("publicKey", "SSH public key", provisionOptions.publicKey, false)}${path("overlay", "Overlay directory", provisionOptions.overlay)}<label class="check"><input id="autologin" type="checkbox" ${provisionOptions.autologin ? "checked" : ""}/> Autologin</label></div><div class="card grid"><label class="wide">APT packages (space/newline separated)<textarea id="packages">${safe(provisionOptions.packages)}</textarea></label><label class="wide">Chroot script (stdin, non-interactive)<textarea id="script">${safe(provisionOptions.script)}</textarea></label><label>Script template<select id="templates"><option value="">Choose…</option></select></label><div class="actions"><button id="load-template">Load</button><button id="save-template">Save as</button><button id="rename-template">Rename</button><button id="delete-template">Delete</button></div><label class="check"><input id="clearKeys" type="checkbox" checked/> Clear SSH host keys</label><label class="check"><input id="clearMachineId" type="checkbox" checked/> Clear machine-id</label><label class="check"><input id="firstBoot" type="checkbox" checked/> First-boot identity service</label></div><div class="actions"><button class="primary" id="run" ${!host.host || !host.root ? "disabled" : ""}>Run provisioning</button><button id="cancel">Cancel</button></div>`); void setupProvision(); }
  if (page === "Recovery") { shell("SSH Recovery", "Reboot a running Jetson into forced recovery over SSH. Available on all platforms.", `<div class="warning">Requires a bootable device, SSH access and a trusted host key in ~/.ssh/known_hosts. Otherwise use FC REC + GND or RECOVERY + RESET.</div><div class="card grid"><label>Host/IP<input id="ssh-host"/></label><label>Port<input id="port" value="22"/></label><label>Username<input id="user"/></label><label>SSH password<input id="ssh-pass" type="password"/></label><label>Sudo password (optional)<input id="sudo-pass" type="password"/></label></div><button class="primary" id="reboot">Request forced recovery</button>`); $("#reboot").onclick = () => { if (!confirmDanger("Reboot the device into Recovery mode?")) return; void Recovery.trigger({ host: val("ssh-host"), port: val("port"), user: val("user"), password: val("ssh-pass"), sudoPassword: val("sudo-pass") }).then(() => { log("Waiting for USB Recovery 0955:7X23"); page = "Devices"; render(); }).catch(fail); }; }
  if (page === "Download") { shell("Download images", "Use a direct HTTP(S) link. Some NVIDIA sources require login, which this app does not provide.", `<div class="card"><p class="hint">Official references: developer.nvidia.com/embedded/jetson-linux-archive · developer.nvidia.com/embedded/jetpack</p><div class="grid"><label class="wide">Direct URL<input id="url" placeholder="https://…"/></label>${path("download-dir", "Save directory", config.downloadDir)}<label>Filename (optional)<input id="filename"/></label><label>Proxy override (HTTP/HTTPS/SOCKS5)<input id="download-proxy" value="${safe(config.proxy.enabled ? config.proxy.url : "")}"/></label></div></div><div class="actions"><button class="primary" id="download">Download</button><button id="cancel">Cancel</button></div>`); $("#download").onclick = () => { const url = val("url"), directory = val("download-dir"), filename = val("filename"), proxyUrl = val("download-proxy"); config.downloadDir = directory; void Environment.saveConfig(config).catch(fail); void stream(channel => Download.start({ url, directory, filename, proxyUrl }, channel), progress => { $("#status").textContent = progress.total > 0 ? `${Math.round(progress.bytes / progress.total * 100)}%` : `${Math.round(progress.bytes / 1048576)} MiB`; log(`${progress.bytes} / ${progress.total || "?"} bytes · ${progress.file}`); }); }; $("#cancel").onclick = () => void Download.cancel().catch(fail); }
  if (page === "Settings") { shell("Settings", "Saved locally. SSH, sudo and device passwords are never stored.", `<div class="card grid">${path("settings-l4t", "Linux_for_Tegra", config.l4t)}${path("workspace", "Workspace", config.workspace)}${path("settings-download", "Download directory", config.downloadDir)}<label>Maximum log lines<input id="log-limit" type="number" min="100" value="${config.logLimit}"/></label><label class="check"><input id="proxy-enabled" type="checkbox" ${config.proxy.enabled ? "checked" : ""}/> Enable proxy</label><label>HTTP/HTTPS/SOCKS5 proxy URL<input id="proxy-url" value="${safe(config.proxy.url)}"/></label><label class="check wide"><input id="remember" type="checkbox" ${config.proxy.rememberCredentials ? "checked" : ""}/> Remember proxy credentials (stored on disk; security risk)</label></div><div class="actions"><button class="primary" id="save-settings">Save settings</button><button id="test-proxy">Test proxy</button></div>`); $("#save-settings").onclick = () => { config = { l4t: val("settings-l4t"), workspace: val("workspace"), downloadDir: val("settings-download"), logLimit: Number(val("log-limit")), proxy: { enabled: check("proxy-enabled"), url: val("proxy-url"), rememberCredentials: check("remember") } }; void Environment.saveConfig(config).then(() => { $("#status").textContent = "Settings saved"; }).catch(fail); }; $("#test-proxy").onclick = () => void Download.testProxy(val("proxy-url")).then(() => { $("#status").textContent = "Proxy reachable"; }).catch(fail); }
}
async function setupProvision() { const password = $<HTMLInputElement>("#password"); $("#show-password").onclick = () => { password.type = password.type === "password" ? "text" : "password"; }; $("#random").onclick = () => void Provision.generatePassword().then(value => { password.value = value; }).catch(fail); const select = $<HTMLSelectElement>("#templates"); const refresh = async () => { select.replaceChildren(new Option("Choose…", "")); for (const template of await Provision.listTemplates()) select.add(new Option(template.name + (template.builtIn ? " · built-in" : ""), template.name)); }; void refresh().catch(fail); $("#load-template").onclick = () => void Provision.loadTemplate(select.value).then(template => { $<HTMLTextAreaElement>("#script").value = template.script; }).catch(fail); $("#save-template").onclick = () => { const name = prompt("Template name"); if (name) void Provision.saveTemplate(name, val("script")).then(refresh).catch(fail); }; $("#rename-template").onclick = () => { const name = prompt("New name"); if (name && select.value) void Provision.renameTemplate(select.value, name).then(refresh).catch(fail); }; $("#delete-template").onclick = () => { if (select.value && confirm(`Delete ${select.value}?`)) void Provision.deleteTemplate(select.value).then(refresh).catch(fail); }; $("#run").onclick = () => { provisionOptions = { username: val("username"), hostname: val("hostname"), password: password.value, publicKey: val("publicKey"), overlay: val("overlay"), autologin: check("autologin"), packages: val("packages"), script: $<HTMLTextAreaElement>("#script").value, clearKeys: check("clearKeys"), clearMachineId: check("clearMachineId"), firstBoot: check("firstBoot") }; if (!confirmDanger(`Run rootfs provisioning?\n\nFull chroot script:\n${provisionOptions.script || "(none)"}`)) return; void stream(channel => Provision.run(config.l4t, provisionOptions, channel), log); }; $("#cancel").onclick = () => void Provision.cancel().catch(fail); }
$("#copy").onclick = () => void navigator.clipboard.writeText(lines.join("\n")).catch(fail);
$("#save").onclick = () => { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([lines.join("\n")], { type: "text/plain" })); link.download = "nvflasher.log"; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); };
$("#hide").onclick = () => { $("#drawer").classList.toggle("hidden"); $("#hide").textContent = $("#drawer").classList.contains("hidden") ? "Show" : "Hide"; };
events.devicesChanged.on(next => { devices = next; $("#device-count").textContent = `${devices.filter(device => device.mode === "recovery").length} recovery devices`; if (page === "Devices") render(); });
try { config = await Environment.getConfig(); host = await Environment.capabilities(); provisionOptions.password = await Provision.generatePassword(); devices = await Devices.list(); render(); if (host.host) void Devices.startWatch().catch(fail); if (!sessionStorage.getItem("eula-notice")) { sessionStorage.setItem("eula-notice", "1"); log("NVIDIA BSP is subject to NVIDIA EULA. Flashing may erase data. Proceed at your own risk."); } } catch (error) { fail(error); }
