// Code generated by `mygo generate`. DO NOT EDIT.

import { call, event, type Channel } from "mygo-runtime";

// ---- Types ----

export interface Check {
  name: string;
  status: string;
  hint: string;
}

export interface Config {
  l4t: string;
  workspace: string;
  downloadDir: string;
  logLimit: number;
  proxy: Proxy;
  flash?: Options;
  provision?: ProvisionForm;
}

export interface Device {
  path: string;
  product: string;
  mode: string;
  boardIds: string;
  release: string;
}

export interface DownloadRequest {
  url: string;
  directory: string;
  filename: string;
  proxyUrl: string;
  sha256: string;
}

export interface InstallPlan {
  distribution: string;
  packages: string[];
  commands: string[][];
}

export interface Model {
  id: string;
  name: string;
  release: string;
  board: string;
  packages: Package[];
}

export interface Options {
  board: string;
  device: string;
  nvme: string;
  qspi: string;
  erase: boolean;
  showLogs: boolean;
}

export interface Package {
  name: string;
  url: string;
  sha1: string;
}

export interface Preset {
  name: string;
  options: Options;
}

export interface Progress {
  bytes: number;
  total: number;
  file: string;
  rate: number;
  eta: number;
}

export interface ProvisionForm {
  username: string;
  hostname: string;
  autologin: boolean;
  publicKey: string;
  packages: string;
  script: string;
  overlay: string;
  clearKeys: boolean;
  clearMachineId: boolean;
  firstBoot: boolean;
}

export interface ProvisionOptions {
  username: string;
  password: string;
  hostname: string;
  autologin: boolean;
  publicKey: string;
  packages: string;
  script: string;
  overlay: string;
  clearKeys: boolean;
  clearMachineId: boolean;
  firstBoot: boolean;
}

export interface Proxy {
  enabled: boolean;
  url: string;
  rememberCredentials: boolean;
}

export interface Report {
  checks: Check[];
  version: string;
  boards: string[];
}

export interface Request {
  host: string;
  port: string;
  user: string;
  password: string;
  sudoPassword: string;
}

export interface Status {
  host: boolean;
  root: boolean;
  checks: Check[];
}

export interface Template {
  name: string;
  script: string;
  builtIn: boolean;
}

// ---- Services ----

export const Environment = {
  browse(directory: boolean): Promise<string> {
    return call("Environment.Browse", directory);
  },
  capabilities(): Promise<Status> {
    return call("Environment.Capabilities");
  },
  detect(dir: string): Promise<Report> {
    return call("Environment.Detect", dir);
  },
  getConfig(): Promise<Config> {
    return call("Environment.GetConfig");
  },
  installDependencies(lines: Channel<string>): Promise<void> {
    return call("Environment.InstallDependencies", lines);
  },
  installPlan(): Promise<InstallPlan> {
    return call("Environment.InstallPlan");
  },
  presets(): Promise<Preset[]> {
    return call("Environment.Presets");
  },
  restartAsRoot(): Promise<void> {
    return call("Environment.RestartAsRoot");
  },
  restartWithSudo(password: string): Promise<void> {
    return call("Environment.RestartWithSudo", password);
  },
  saveConfig(value: Config): Promise<void> {
    return call("Environment.SaveConfig", value);
  },
} as const;

export const Devices = {
  list(): Promise<Device[]> {
    return call("Devices.List");
  },
  startWatch(): Promise<void> {
    return call("Devices.StartWatch");
  },
} as const;

export const Flash = {
  cancel(): Promise<void> {
    return call("Flash.Cancel");
  },
  start(dir: string, opts: Options, lines: Channel<string>): Promise<void> {
    return call("Flash.Start", dir, opts, lines);
  },
} as const;

export const Massflash = {
  cancel(): Promise<void> {
    return call("Massflash.Cancel");
  },
  flash(dir: string, count: number, show: boolean, lines: Channel<string>): Promise<void> {
    return call("Massflash.Flash", dir, count, show, lines);
  },
  generate(dir: string, opts: Options, count: number, lines: Channel<string>): Promise<void> {
    return call("Massflash.Generate", dir, opts, count, lines);
  },
} as const;

export const Provision = {
  cancel(): Promise<void> {
    return call("Provision.Cancel");
  },
  deleteTemplate(name: string): Promise<void> {
    return call("Provision.DeleteTemplate", name);
  },
  generatePassword(): Promise<string> {
    return call("Provision.GeneratePassword");
  },
  listTemplates(): Promise<Template[]> {
    return call("Provision.ListTemplates");
  },
  loadTemplate(name: string): Promise<Template> {
    return call("Provision.LoadTemplate", name);
  },
  renameTemplate(oldName: string, newName: string): Promise<void> {
    return call("Provision.RenameTemplate", oldName, newName);
  },
  run(dir: string, opts: ProvisionOptions, lines: Channel<string>): Promise<void> {
    return call("Provision.Run", dir, opts, lines);
  },
  saveTemplate(name: string, script: string): Promise<void> {
    return call("Provision.SaveTemplate", name, script);
  },
} as const;

export const Recovery = {
  trigger(request: Request): Promise<void> {
    return call("Recovery.Trigger", request);
  },
} as const;

export const Download = {
  cancel(): Promise<void> {
    return call("Download.Cancel");
  },
  show(path: string): Promise<void> {
    return call("Download.Show", path);
  },
  start(request: DownloadRequest, events: Channel<Progress>): Promise<void> {
    return call("Download.Start", request, events);
  },
  testProxy(address: string): Promise<void> {
    return call("Download.TestProxy", address);
  },
  testProxyFor(address: string, target: string): Promise<void> {
    return call("Download.TestProxyFor", address, target);
  },
} as const;

export const Setup = {
  cancel(): Promise<void> {
    return call("Setup.Cancel");
  },
  download(modelID: string, directory: string, proxyURL: string, lines: Channel<string>): Promise<void> {
    return call("Setup.Download", modelID, directory, proxyURL, lines);
  },
  location(modelID: string, directory: string): Promise<string> {
    return call("Setup.Location", modelID, directory);
  },
  models(): Promise<Model[]> {
    return call("Setup.Models");
  },
  prepare(modelID: string, directory: string, lines: Channel<string>): Promise<string> {
    return call("Setup.Prepare", modelID, directory, lines);
  },
} as const;

// ---- Events ----

/** Events sent by the Go side. Subscribe with `events.name.on(listener)`. */
export const events = {
  devicesChanged: event<Device[]>("devices:changed"),
} as const;
